apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8s-job-cleaner
  namespace: {{.YOUR_NAME_SPACE}}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: norbertvannobelen/k8s-job-cleaner:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            resources:
              limits:
                cpu: "1"
                memory: 300Mi
              requests:
                cpu: 10m
                memory: 300Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 1 1 * * *
  successfulJobsHistoryLimit: 1
  suspend: false
